---
kind: pipeline
type: docker
name: start szenario

steps:
    - name: etcd
      image: "bitnami/etcd:latest"
      environment:
          ALLOW_NONE_AUTHENTICATION: yes
          ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      detach: true

    - name: nats
      image: nats
      detach: true

    - name: redis
      image: "bitnami/redis:latest"
      environment:
          ALLOW_EMPTY_PASSWORD: yes
      detach: true

    # depends_on:
    # - greeterdocker
    # - counterdocker
    # - loggerdocker
    # - clientdocker

    # ---
    # kind: pipeline
    # type: docker
    # name: start services

    # steps:
    - name: greeter
      image: docker.pkg.github.com/vesose/example-micro/greeter:latest
      environment:
          ALLOW_NONE_AUTHENTICATION: yes
      commands:
          - sleep 5
          - /app/greeter-service --registry_address=etcd:2379
      detach: true

    - name: counter
      image: docker.pkg.github.com/vesose/example-micro/counter:latest
      environment:
          ALLOW_NONE_AUTHENTICATION: yes
      commands:
          - sleep 5
          - /app/counter-service --registry_address=etcd:2379  --broker_address=nats:4222
      detach: true

    - name: logger
      image: docker.pkg.github.com/vesose/example-micro/logger:latest
      environment:
          ALLOW_NONE_AUTHENTICATION: yes
      commands:
          - sleep 5
          - /app/logger-service --registry_address=etcd:2379  --broker_address=nats:4222 --store_address=redis:6379  --store_table=sleeper
      detach: true

    # depends_on:
    #     - start servers

    # ---
    # kind: pipeline
    # type: docker
    # name: start client

    # steps:
    - name: client
      image: docker.pkg.github.com/vesose/example-micro/client:latest
      environment:
          ALLOW_NONE_AUTHENTICATION: yes
      commands:
          - sleep 5
          - /app/client --registry_address=etcd:2379  --store_address=redis:6379  --store_table=sleeper

# depends_on:
#     - start services

# als Secret dockerconfig
# das AuthToken bekommen Sie als Ergebnis des Aufrufs
# echo -u username:token | base64
# {
# 	"auths": {
# 		"docker.pkg.github.com": {
# 			"auth": "YW11cmRhY2E6c3VwZXJzZWNyZXRwYXNzd29yZA=="
# 		}
# 	}
# }

image_pull_secrets:
    - dockerconfig
