image: golang:1.14.3

stages:
  - lint
  - test

make_lint:
  image: golangci/golangci-lint
  stage: lint
  script:
    - golangci-lint run

unit_tests:
  stage: test
  script:
    - go test -v ./... -coverprofile .testCoverage.txt
