image: golang:1.14.3

stages:
  - lint
  - test
  - build

make_lint:
  image: golangci/golangci-lint
  stage: lint
  script:
    - golangci-lint run

unit_tests:
  stage: test
  script:
    - go test -v ./... -coverprofile .testCoverage.txt

client_docker:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/client/service/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
