version: "3"
services:
    etcd:
        image: "bitnami/etcd:latest"
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    nats:
        image: nats
    redis:
        image: "bitnami/redis:latest"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
    counter-service:
        image: docker.pkg.github.com/vesose/example-micro/counter:latest
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        command: --registry_address=etcd:2379 --broker_address=nats:4222
        links:
            - etcd
            - nats
    greeter-service:
        image: docker.pkg.github.com/vesose/example-micro/greeter:latest
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        command: --registry_address=etcd:2379
        links:
            - etcd
    logger-service:
        image: docker.pkg.github.com/vesose/example-micro/logger:latest
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        command: --registry_address=etcd:2379 --broker_address=nats://nats:4222  --store_address=redis:6379
        links:
            - etcd
            - nats
    client:
        image: docker.pkg.github.com/vesose/example-micro/client:latest
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        command: --registry_address=etcd:2379
        links:
            - etcd
