version: "3"
services:
    etcd:
        image: "bitnami/etcd:latest"
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    nats:
        image: nats
    redis:
        image: "bitnami/redis:latest"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
    counter-service:
        build:
            context: .
            dockerfile: counter/service/Dockerfile
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        command: --registry_address=etcd:2379 --broker_address=nats:4222
        links:
            - etcd
            - nats
    greeter-service:
        build:
            context: .
            dockerfile: greeter/service/Dockerfile
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        command: --registry_address=etcd:2379
        links:
            - etcd
    logwriter-service:
        build:
            context: .
            dockerfile: logwriter/service/Dockerfile
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        command: --registry_address=etcd:2379 --broker_address=nats://nats:4222 --store_address=redis:6379 --store_table=sleeper
        links:
            - etcd
            - nats
    client:
        build:
            context: .
            dockerfile: client/service/Dockerfile
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        command: --registry_address=etcd:2379 --store_address=redis:6379  --store_table=sleeper
        links:
            - etcd
