version: "3"
services:
    consul:
        command: -server -bootstrap -rejoin
        image: progrium/consul:latest
        ports:
            - "8300:8300"
            - "8400:8400"
            - "8500:8500"
            - "8600:53/udp"
    counter-service:
        build:
            context: .
            dockerfile: counter-service/Dockerfile
        command: --registry_address=consul:8500
        links:
            - consul
    greeter-service:
        build:
            context: .
            dockerfile: greeter-service/Dockerfile
        command: --registry_address=consul:8500
        links:
            - consul
    client:
        build:
            context: .
            dockerfile: client/Dockerfile
        command: --registry_address=consul:8500
        links:
            - consul
